version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.8
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

push-server: &push-server
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install modules
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Unit test
          command: yarn test:unit

  build-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Build test
          command: yarn build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

  install-push-server:
    <<: *push-server
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-push-server-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-push-server-dependencies-
      - run:
          name: Install modules
          command: yarn install
          working_directory: packages/push-server
      - save_cache:
          paths:
            - node_modules
          key: v1-push-server-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}

  deploy-push-server:
    <<: *push-server
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-push-server-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-push-server-dependencies-
      - run:
          name: Install serverless
          command: sudo yarn global add serverless
          working_directory: packages/push-server
      - run:
          name: Deploy
          command: sls deploy
          working_directory: packages/push-server

workflows:
  version: 2
  execute_process:
    jobs:
      - install:
          filters:
            branches:
              # only: /.*/
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - test:
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
              # only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - build-test:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
              # only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - install-push-server:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^push-server-v[0-9]+(\.[0-9]+){2}$/
      - deploy-push-server:
          requires:
            - install-push-server
          filters:
            branches:
              only: /.*/
            tags:
              only: /^push-server-v[0-9]+(\.[0-9]+){2}$/
