version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.8
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

push-manager: &push-manager
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install modules
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Unit test
          command: yarn test:unit

  build-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Build test
          command: yarn build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

  install-push-manager:
    <<: *push-manager
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-push-manager-dependencies-{{ checksum "packages/push-manager/package.json" }}--{{ checksum "packages/push-manager/yarn.lock" }}
          - v1-push-manager-dependencies-
      - run:
          name: Install modules
          command: yarn install
          working_directory: packages/push-manager
      - save_cache:
          paths:
            - packages/push-manager/node_modules
          key: v1-push-manager-dependencies-{{ checksum "packages/push-manager/package.json" }}--{{ checksum "packages/push-manager/arn.lock" }}

  deploy-push-manager:
    <<: *push-manager
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-push-manager-dependencies-{{ checksum "packages/push-manager/package.json" }}--{{ checksum "packages/push-manager/yarn.lock" }}
          - v1-push-manager-dependencies-
      - run:
          name: Install serverless
          command: sudo yarn global add serverless
          working_directory: packages/push-manager
      - run:
          name: Check files
          command: ls
          working_directory: packages/push-manager
      - run:
          name: Deploy
          command: sls deploy
          working_directory: packages/push-manager

workflows:
  version: 2
  execute_process:
    jobs:
      - install:
          filters:
            branches:
              # only: /.*/
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - test:
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
              # only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - build-test:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
              # only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - install-push-manager:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^push-manager-v[0-9]+(\.[0-9]+){2}$/
      - deploy-push-manager:
          requires:
            - install-push-manager
          filters:
            branches:
              only: /.*/
            tags:
              only: /^push-manager-v[0-9]+(\.[0-9]+){2}$/
