service:
  name: ${self:custom.NAME}

frameworkVersion: ">=1.31.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - kms:Decrypt
      Resource:
        - ${env:AWS_KMS_ARN}

custom:
  NAME: try-pwa-push-manager

package:
  excludeDevDependencies: true
  exclude:
    - .*
    - package.json
    - yarn.lock
    - firebase-access-key.json
    - node_modules/aws-sdk/**

functions:
  notify:
    handler: handler.notify
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: '/notify'
          method: post

resources:
 Resources:
   S3Bucketi:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: storage.try-pwa.mya-ake.org
